### ISSUE TITLE
Summarize the differences between different versions of legacy DTD files

### ISSUE THREAD

**Issue by darrensiegel** [Simon-Initiative/course-digest#20]
Some legacy courses contain resources (workbook pages, inline assessments) that are still using previous (i.e., older) versions of their respective DTDs.  These different versions vary the structure of the XML sometimes in some considerable ways.  We need an analysis done that can summarize the ways in which different versions of a DTD change over time, so that we can understand how this will impact the course migration effort and the course-digest tool itself. 

The DTDs that are of interest are:

1. A2 (`oli_assessment_2_4.dtd`)
2. Inline (`oli_inline_assessment_1_4.dtd`)
3. Learning content (`oli_learning_content_3_8.dtd`)
4. Workbook page (`oli_workbook_page_3_8`)

For each of the above DTDs, we need a summarization of the delta between their latest version (listed above) and the most recent version.

**Comment by darrensiegel** [comment]
@rgachuhi Is there perhaps any tooling or support in the OLI Legacy codebase that can convert older versions of a DTD to a new version?

**Comment by rgachuhi** [comment]
> @rgachuhi Is there perhaps any tooling or support in the OLI Legacy codebase that can convert older versions of a DTD to a new version?

Unfortunately, Legacy OLI has no such too. Converting a resource from older versions of a DTD to a new version is a manual process, usually undertaken on a PRN basis. The legacy system has no problem with this since it already supports backward DTD versions.
