### ISSUE TITLE
Learn by doing shows up as separate Content and Activity

### ISSUE THREAD

**Issue by bitbldr** [Simon-Initiative/course-digest#3]
The result activity should probably have the "Learn by doing" designation

<img width="1165" alt="Screen Shot 2021-03-09 at 10 58 23 AM" src="https://user-images.githubusercontent.com/6248894/110499579-61f10f00-80c6-11eb-9ba0-44bdf8254f66.png">

**Comment by darrensiegel** [comment]
I'm not sure what the issue here is. Can you elaborate?

**Comment by bitbldr** [comment]
Ah, this is actually a header in the original assessment. It looks like it is actually doing the correct thing here.
