### ISSUE TITLE
HTML/XML escape entities not supported

### ISSUE THREAD

**Issue by darrensiegel** [Simon-Initiative/course-digest#54]
Many/most HTML entities do not seem to be supported during migration.  Take the following example paragraph:

`<p>What is 1 &times; 2 equal to?</p>`

The `&times;` migrates as that literal string, and renders to students as such.

**Comment by gjbunyea** [comment]
Specific Example:
SVN: https://svn.oli.cmu.edu/svn/content/editor/projects/echo-oli-cmu-edu/wellstart-v8fhrc86/branches/v_1_2-echo/content/x-oli-workbook_page/ab307ad473584905b8dd8ad2b5cd3522.xml
INGESTED: https://tokamak.oli.cmu.edu/authoring/project/wellstart/resource/letaposs_pause_and_reflect_str_792h1
