### ISSUE TITLE
Migrated course appears as already published

### ISSUE THREAD

**Issue by gjbunyea** [Simon-Initiative/course-digest#67]
A freshly ingested course is showing as already published, with pending changes.
No changes have been made, and the course has not been published

![image](https://user-images.githubusercontent.com/18299544/182636060-18604841-170f-4b94-a76e-ede01d2bed54.png)

A repeated ingestion from the same digest results in the same effect. 

The digest and SVN link are below
[wellstart_1-2.zip](https://github.com/Simon-Initiative/course-digest/files/9252441/wellstart_1-2.zip)
https://svn.oli.cmu.edu/svn/content/editor/projects/echo-oli-cmu-edu/wellstart-v8fhrc86/branches/v_1_2-echo

**Comment by gjbunyea** [comment]
We believe this to be related to ingestion of multiple organizations simultaneously - the course gets published in order to facilitate multiple products being created for multiple organizations.

**Comment by darrensiegel** [comment]
This is correct. A course must be published for it to be able to have products created for it.
