### ISSUE TITLE
Allow migration of specific organization (not all)

### ISSUE THREAD

**Issue by gjbunyea** [Simon-Initiative/course-digest#68]
Current work is being done to provide a mechanism to migrate all organizations from a single package into one project, as multiple products. I would like the option to migrate ONLY a specific organization. 

This would facilitate leaving information contained in unnecessary organizations behind, streamlining the migration.

**Comment by darrensiegel** [comment]
It might be easier to handle this outside of the tool by simply renaming the files for the organizations that are to be ignored.
